export interface Country {
  /** Dutch country name */
  name: string;
  /** ISO 3166-1 alpha-2 code */
  code: string;
  /** International dial code, without "+" */
  dial: string;
}

/** Countries in Dutch, sorted alphabetically, with Belgium/Netherlands pinned on top of the select. */
export const countries: Country[] = [
  { name: "Afghanistan", code: "AF", dial: "93" },
  { name: "Albanië", code: "AL", dial: "355" },
  { name: "Algerije", code: "DZ", dial: "213" },
  { name: "Andorra", code: "AD", dial: "376" },
  { name: "Angola", code: "AO", dial: "244" },
  { name: "Argentinië", code: "AR", dial: "54" },
  { name: "Armenië", code: "AM", dial: "374" },
  { name: "Aruba", code: "AW", dial: "297" },
  { name: "Australië", code: "AU", dial: "61" },
  { name: "Azerbeidzjan", code: "AZ", dial: "994" },
  { name: "Bahama's", code: "BS", dial: "1" },
  { name: "Bahrein", code: "BH", dial: "973" },
  { name: "Bangladesh", code: "BD", dial: "880" },
  { name: "Barbados", code: "BB", dial: "1" },
  { name: "Belarus", code: "BY", dial: "375" },
  { name: "België", code: "BE", dial: "32" },
  { name: "Belize", code: "BZ", dial: "501" },
  { name: "Benin", code: "BJ", dial: "229" },
  { name: "Bolivia", code: "BO", dial: "591" },
  { name: "Bosnië en Herzegovina", code: "BA", dial: "387" },
  { name: "Botswana", code: "BW", dial: "267" },
  { name: "Brazilië", code: "BR", dial: "55" },
  { name: "Brunei Darussalam", code: "BN", dial: "673" },
  { name: "Bulgarije", code: "BG", dial: "359" },
  { name: "Burkina Faso", code: "BF", dial: "226" },
  { name: "Burundi", code: "BI", dial: "257" },
  { name: "Cambodja", code: "KH", dial: "855" },
  { name: "Canada", code: "CA", dial: "1" },
  { name: "Centraal-Afrikaanse Republiek", code: "CF", dial: "236" },
  { name: "Chili", code: "CL", dial: "56" },
  { name: "China", code: "CN", dial: "86" },
  { name: "Colombia", code: "CO", dial: "57" },
  { name: "Comoren", code: "KM", dial: "269" },
  { name: "Congo", code: "CG", dial: "242" },
  { name: "Costa Rica", code: "CR", dial: "506" },
  { name: "Curaçao", code: "CW", dial: "599" },
  { name: "Cyprus", code: "CY", dial: "357" },
  { name: "Democratische Republiek Congo", code: "CD", dial: "243" },
  { name: "Denemarken", code: "DK", dial: "45" },
  { name: "Dominicaanse Republiek", code: "DO", dial: "1" },
  { name: "Duitsland", code: "DE", dial: "49" },
  { name: "Ecuador", code: "EC", dial: "593" },
  { name: "Egypte", code: "EG", dial: "20" },
  { name: "El Salvador", code: "SV", dial: "503" },
  { name: "Estland", code: "EE", dial: "372" },
  { name: "Ethiopië", code: "ET", dial: "251" },
  { name: "Faeröer", code: "FO", dial: "298" },
  { name: "Fiji", code: "FJ", dial: "679" },
  { name: "Filippijnen", code: "PH", dial: "63" },
  { name: "Finland", code: "FI", dial: "358" },
  { name: "Frankrijk", code: "FR", dial: "33" },
  { name: "Gabon", code: "GA", dial: "241" },
  { name: "Gambia", code: "GM", dial: "220" },
  { name: "Georgië", code: "GE", dial: "995" },
  { name: "Ghana", code: "GH", dial: "233" },
  { name: "Gibraltar", code: "GI", dial: "350" },
  { name: "Griekenland", code: "GR", dial: "30" },
  { name: "Groenland", code: "GL", dial: "299" },
  { name: "Guatemala", code: "GT", dial: "502" },
  { name: "Guinee", code: "GN", dial: "224" },
  { name: "Haïti", code: "HT", dial: "509" },
  { name: "Honduras", code: "HN", dial: "504" },
  { name: "Hong Kong", code: "HK", dial: "852" },
  { name: "Hongarije", code: "HU", dial: "36" },
  { name: "IJsland", code: "IS", dial: "354" },
  { name: "Ierland", code: "IE", dial: "353" },
  { name: "India", code: "IN", dial: "91" },
  { name: "Indonesië", code: "ID", dial: "62" },
  { name: "Irak", code: "IQ", dial: "964" },
  { name: "Israël", code: "IL", dial: "972" },
  { name: "Italië", code: "IT", dial: "39" },
  { name: "Ivoorkust", code: "CI", dial: "225" },
  { name: "Jamaica", code: "JM", dial: "1" },
  { name: "Japan", code: "JP", dial: "81" },
  { name: "Jemen", code: "YE", dial: "967" },
  { name: "Jordanië", code: "JO", dial: "962" },
  { name: "Kaapverdische Eilanden", code: "CV", dial: "238" },
  { name: "Kameroen", code: "CM", dial: "237" },
  { name: "Kazachstan", code: "KZ", dial: "7" },
  { name: "Kenia", code: "KE", dial: "254" },
  { name: "Kirgizië", code: "KG", dial: "996" },
  { name: "Koeweit", code: "KW", dial: "965" },
  { name: "Kosovo", code: "XK", dial: "383" },
  { name: "Kroatië", code: "HR", dial: "385" },
  { name: "Laos", code: "LA", dial: "856" },
  { name: "Letland", code: "LV", dial: "371" },
  { name: "Libanon", code: "LB", dial: "961" },
  { name: "Liberia", code: "LR", dial: "231" },
  { name: "Libië", code: "LY", dial: "218" },
  { name: "Liechtenstein", code: "LI", dial: "423" },
  { name: "Litouwen", code: "LT", dial: "370" },
  { name: "Luxemburg", code: "LU", dial: "352" },
  { name: "Macau", code: "MO", dial: "853" },
  { name: "Madagaskar", code: "MG", dial: "261" },
  { name: "Malawi", code: "MW", dial: "265" },
  { name: "Malediven", code: "MV", dial: "960" },
  { name: "Maleisië", code: "MY", dial: "60" },
  { name: "Mali", code: "ML", dial: "223" },
  { name: "Malta", code: "MT", dial: "356" },
  { name: "Marokko", code: "MA", dial: "212" },
  { name: "Mauritius", code: "MU", dial: "230" },
  { name: "Mexico", code: "MX", dial: "52" },
  { name: "Moldavië", code: "MD", dial: "373" },
  { name: "Monaco", code: "MC", dial: "377" },
  { name: "Mongolië", code: "MN", dial: "976" },
  { name: "Montenegro", code: "ME", dial: "382" },
  { name: "Mozambique", code: "MZ", dial: "258" },
  { name: "Myanmar", code: "MM", dial: "95" },
  { name: "Namibië", code: "NA", dial: "264" },
  { name: "Nederland", code: "NL", dial: "31" },
  { name: "Nepal", code: "NP", dial: "977" },
  { name: "Nicaragua", code: "NI", dial: "505" },
  { name: "Nieuw-Zeeland", code: "NZ", dial: "64" },
  { name: "Niger", code: "NE", dial: "227" },
  { name: "Nigeria", code: "NG", dial: "234" },
  { name: "Noord-Macedonië", code: "MK", dial: "389" },
  { name: "Noorwegen", code: "NO", dial: "47" },
  { name: "Oeganda", code: "UG", dial: "256" },
  { name: "Oekraïne", code: "UA", dial: "380" },
  { name: "Oezbekistan", code: "UZ", dial: "998" },
  { name: "Oman", code: "OM", dial: "968" },
  { name: "Oostenrijk", code: "AT", dial: "43" },
  { name: "Pakistan", code: "PK", dial: "92" },
  { name: "Panama", code: "PA", dial: "507" },
  { name: "Paraguay", code: "PY", dial: "595" },
  { name: "Peru", code: "PE", dial: "51" },
  { name: "Polen", code: "PL", dial: "48" },
  { name: "Portugal", code: "PT", dial: "351" },
  { name: "Qatar", code: "QA", dial: "974" },
  { name: "Roemenië", code: "RO", dial: "40" },
  { name: "Rusland", code: "RU", dial: "7" },
  { name: "Rwanda", code: "RW", dial: "250" },
  { name: "San Marino", code: "SM", dial: "378" },
  { name: "Saoedi-Arabië", code: "SA", dial: "966" },
  { name: "Senegal", code: "SN", dial: "221" },
  { name: "Servië", code: "RS", dial: "381" },
  { name: "Seychellen", code: "SC", dial: "248" },
  { name: "Singapore", code: "SG", dial: "65" },
  { name: "Sint Maarten", code: "SX", dial: "1" },
  { name: "Slovenië", code: "SI", dial: "386" },
  { name: "Slowakije", code: "SK", dial: "421" },
  { name: "Soedan", code: "SD", dial: "249" },
  { name: "Spanje", code: "ES", dial: "34" },
  { name: "Sri Lanka", code: "LK", dial: "94" },
  { name: "Suriname", code: "SR", dial: "597" },
  { name: "Tadzjikistan", code: "TJ", dial: "992" },
  { name: "Taiwan", code: "TW", dial: "886" },
  { name: "Tanzania", code: "TZ", dial: "255" },
  { name: "Thailand", code: "TH", dial: "66" },
  { name: "Togo", code: "TG", dial: "228" },
  { name: "Trinidad en Tobago", code: "TT", dial: "1" },
  { name: "Tsjechië", code: "CZ", dial: "420" },
  { name: "Tunesië", code: "TN", dial: "216" },
  { name: "Turkije", code: "TR", dial: "90" },
  { name: "Turkmenistan", code: "TM", dial: "993" },
  { name: "Uruguay", code: "UY", dial: "598" },
  { name: "Vaticaanstad", code: "VA", dial: "379" },
  { name: "Venezuela", code: "VE", dial: "58" },
  { name: "Verenigd Koninkrijk", code: "GB", dial: "44" },
  { name: "Verenigde Arabische Emiraten", code: "AE", dial: "971" },
  { name: "Verenigde Staten", code: "US", dial: "1" },
  { name: "Vietnam", code: "VN", dial: "84" },
  { name: "Zambia", code: "ZM", dial: "260" },
  { name: "Zimbabwe", code: "ZW", dial: "263" },
  { name: "Zuid-Afrika", code: "ZA", dial: "27" },
  { name: "Zuid-Korea", code: "KR", dial: "82" },
  { name: "Zweden", code: "SE", dial: "46" },
  { name: "Zwitserland", code: "CH", dial: "41" },
];

/** Belgium and the Netherlands first, then the rest alphabetically. */
export const countriesForSelect: Country[] = [
  ...countries.filter((c) => c.code === "BE" || c.code === "NL"),
  ...countries.filter((c) => c.code !== "BE" && c.code !== "NL"),
];

export const arrivalTimeSlots: string[] = [
  "Weet ik niet",
  ...Array.from({ length: 8 }, (_, i) => {
    const from = 16 + i;
    const to = (from + 1) % 24;
    return `${String(from % 24).padStart(2, "0")}:00 - ${String(to).padStart(2, "0")}:00`;
  }),
];
