/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KleinLauwRouteImport } from './routes/klein-lauw'
import { Route as GalerijRouteImport } from './routes/galerij'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KleinLauwGalerijRouteImport } from './routes/klein-lauw.galerij'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTarievenRouteImport } from './routes/_authenticated/admin.tarieven'
import { Route as AuthenticatedAdminLocatiesRouteImport } from './routes/_authenticated/admin.locaties'
import { Route as AuthenticatedAdminKalendersyncRouteImport } from './routes/_authenticated/admin.kalendersync'

const KleinLauwRoute = KleinLauwRouteImport.update({
  id: '/klein-lauw',
  path: '/klein-lauw',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerijRoute = GalerijRouteImport.update({
  id: '/galerij',
  path: '/galerij',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KleinLauwGalerijRoute = KleinLauwGalerijRouteImport.update({
  id: '/galerij',
  path: '/galerij',
  getParentRoute: () => KleinLauwRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTarievenRoute =
  AuthenticatedAdminTarievenRouteImport.update({
    id: '/tarieven',
    path: '/tarieven',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLocatiesRoute =
  AuthenticatedAdminLocatiesRouteImport.update({
    id: '/locaties',
    path: '/locaties',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKalendersyncRoute =
  AuthenticatedAdminKalendersyncRouteImport.update({
    id: '/kalendersync',
    path: '/kalendersync',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/galerij': typeof GalerijRoute
  '/klein-lauw': typeof KleinLauwRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/klein-lauw/galerij': typeof KleinLauwGalerijRoute
  '/admin/kalendersync': typeof AuthenticatedAdminKalendersyncRoute
  '/admin/locaties': typeof AuthenticatedAdminLocatiesRoute
  '/admin/tarieven': typeof AuthenticatedAdminTarievenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/galerij': typeof GalerijRoute
  '/klein-lauw': typeof KleinLauwRouteWithChildren
  '/klein-lauw/galerij': typeof KleinLauwGalerijRoute
  '/admin/kalendersync': typeof AuthenticatedAdminKalendersyncRoute
  '/admin/locaties': typeof AuthenticatedAdminLocatiesRoute
  '/admin/tarieven': typeof AuthenticatedAdminTarievenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/galerij': typeof GalerijRoute
  '/klein-lauw': typeof KleinLauwRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/klein-lauw/galerij': typeof KleinLauwGalerijRoute
  '/_authenticated/admin/kalendersync': typeof AuthenticatedAdminKalendersyncRoute
  '/_authenticated/admin/locaties': typeof AuthenticatedAdminLocatiesRoute
  '/_authenticated/admin/tarieven': typeof AuthenticatedAdminTarievenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/galerij'
    | '/klein-lauw'
    | '/admin'
    | '/klein-lauw/galerij'
    | '/admin/kalendersync'
    | '/admin/locaties'
    | '/admin/tarieven'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/galerij'
    | '/klein-lauw'
    | '/klein-lauw/galerij'
    | '/admin/kalendersync'
    | '/admin/locaties'
    | '/admin/tarieven'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/galerij'
    | '/klein-lauw'
    | '/_authenticated/admin'
    | '/klein-lauw/galerij'
    | '/_authenticated/admin/kalendersync'
    | '/_authenticated/admin/locaties'
    | '/_authenticated/admin/tarieven'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GalerijRoute: typeof GalerijRoute
  KleinLauwRoute: typeof KleinLauwRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/klein-lauw': {
      id: '/klein-lauw'
      path: '/klein-lauw'
      fullPath: '/klein-lauw'
      preLoaderRoute: typeof KleinLauwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerij': {
      id: '/galerij'
      path: '/galerij'
      fullPath: '/galerij'
      preLoaderRoute: typeof GalerijRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klein-lauw/galerij': {
      id: '/klein-lauw/galerij'
      path: '/galerij'
      fullPath: '/klein-lauw/galerij'
      preLoaderRoute: typeof KleinLauwGalerijRouteImport
      parentRoute: typeof KleinLauwRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tarieven': {
      id: '/_authenticated/admin/tarieven'
      path: '/tarieven'
      fullPath: '/admin/tarieven'
      preLoaderRoute: typeof AuthenticatedAdminTarievenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/locaties': {
      id: '/_authenticated/admin/locaties'
      path: '/locaties'
      fullPath: '/admin/locaties'
      preLoaderRoute: typeof AuthenticatedAdminLocatiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kalendersync': {
      id: '/_authenticated/admin/kalendersync'
      path: '/kalendersync'
      fullPath: '/admin/kalendersync'
      preLoaderRoute: typeof AuthenticatedAdminKalendersyncRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminKalendersyncRoute: typeof AuthenticatedAdminKalendersyncRoute
  AuthenticatedAdminLocatiesRoute: typeof AuthenticatedAdminLocatiesRoute
  AuthenticatedAdminTarievenRoute: typeof AuthenticatedAdminTarievenRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminKalendersyncRoute: AuthenticatedAdminKalendersyncRoute,
  AuthenticatedAdminLocatiesRoute: AuthenticatedAdminLocatiesRoute,
  AuthenticatedAdminTarievenRoute: AuthenticatedAdminTarievenRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface KleinLauwRouteChildren {
  KleinLauwGalerijRoute: typeof KleinLauwGalerijRoute
}

const KleinLauwRouteChildren: KleinLauwRouteChildren = {
  KleinLauwGalerijRoute: KleinLauwGalerijRoute,
}

const KleinLauwRouteWithChildren = KleinLauwRoute._addFileChildren(
  KleinLauwRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GalerijRoute: GalerijRoute,
  KleinLauwRoute: KleinLauwRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
